version: '3.4'

services:
  dev:
    image: front-end-monorepo_dev:latest
    build:
      context: ../../
      target: bootstrap
    entrypoint:
      - "yarn"
      - "workspace"
      - "@zooniverse/fe-project"
    command: ["dev"]
    ports:
      - "3000:3000"
    volumes:
      - ../../:/usr/src
      - /usr/src/node_modules
  storybook:
    image: front-end-monorepo_dev:latest
    entrypoint:
      - "yarn"
      - "workspace"
      - "@zooniverse/fe-project"
    command: ["storybook"]
    ports:
      - "9001:9001"
    volumes:
      - ../../:/usr/src
      - /usr/src/node_modules