version: '3.4'

services:
  dev:
    image: front-end-monorepo_dev:latest
    build:
      context: ../../
    entrypoint:
      - "yarn"
      - "workspace"
      - "@zooniverse/fe-project"
    command: ["dev"]
    ports:
      - "3000:3000"
    volumes:
      - ./pages:/usr/src/packages/app-project/pages
      - ./src:/usr/src/packages/app-project/src
      - ./stores:/usr/src/packages/app-project/stores
  storybook:
    image: front-end-monorepo_dev:latest
    entrypoint:
      - "yarn"
      - "workspace"
      - "@zooniverse/fe-project"
    command: ["storybook"]
    ports:
      - "9001:9001"
    volumes:
      - ./pages:/usr/src/packages/app-project/pages
      - ./src:/usr/src/packages/app-project/src
      - ./stores:/usr/src/packages/app-project/stores