version: '3.2'

services:
  dev:
    build:
      context: ../../
    entrypoint:
      - "yarn"
      - "workspace"
      - "@zooniverse/fe-content-pages"
    command: ["dev"]
    ports:
      - "3000:3000"
      - "9001:9001"
    volumes:
      - ../../:/usr/src
      - /usr/src/node_modules