version: '3.2'

services:
  dev:
    image: front-end-monorepo_dev:latest
    build:
      context: ../../
      target: bootstrap
    entrypoint:
      - "yarn"
      - "workspace"
      - "@zooniverse/fe-content-pages"
    command: ["dev"]
    ports:
      - "3000:3000"
      - "9001:9001"
    volumes:
      - ./pages:/usr/src/packages/app-content-pages/pages
      - ./src:/usr/src/packages/app-content-pages/src