language: node_js

node_js:
  - '10'

branches:
  only:
    - master

cache: yarn

install:
  - yarn bootstrap

script:
  - yarn test:ci
  - yarn workspace @zooniverse/fe-content-pages build
  - yarn workspace @zooniverse/fe-project build

after_success:
  - yarn coverage
