version: '3.2'

services:
  dev:
    image: front-end-monorepo_dev:latest
    build:
      context: ../../
    entrypoint:
      - "yarn"
      - "workspace"
      - "@zooniverse/classifier"
    command: ["dev"]
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
    volumes:
      - ../../:/usr/src
      - /usr/src/node_modules
  storybook:
    image: front-end-monorepo_dev:latest
    entrypoint:
      - "yarn"
      - "workspace"
      - "@zooniverse/classifier"
    command: ["storybook"]
    ports:
      - "6006:6006"
    volumes:
      - ../../:/usr/src
      - /usr/src/node_modules