name: test build

on:
  pull_request

jobs:
  build:
    name: Build libraries
    runs-on: ubuntu-latest
    steps:
    # See: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/configuring-a-workflow#using-the-checkout-action
      - uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'

      - run: yarn install --production=false --frozen-lockfile
      - run: yarn workspace @zooniverse/react-components build
      - run: yarn workspace @zooniverse/classifier build
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: packages/*/dist/main.js

  build_project_app:
    name: Build NextJS project app
    runs-on: ubuntu-latest
    needs: build
    env:
      APP_ENV: production
      NODE_ENV: production
      PANOPTES_ENV: production
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
         node-version: '16.x'
         cache: 'yarn'

      - run: yarn install --production=false --frozen-lockfile
      - uses: actions/download-artifact@v2
        with:
          name: build
          path: packages/
      - run: yarn workspace @zooniverse/fe-project build

  build_content_app:
    name: Build NextJS content pages app
    runs-on: ubuntu-latest
    needs: build
    env:
      APP_ENV: production
      NODE_ENV: production
      PANOPTES_ENV: production
      CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
      CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
         node-version: '16.x'
         cache: 'yarn'

      - run: yarn install --production=false --frozen-lockfile
      - uses: actions/download-artifact@v2
        with:
          name: build
          path: packages/
      - run: yarn workspace @zooniverse/fe-content-pages build

  build_storybooks:
    name: Build storybooks
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
         node-version: '16.x'
         cache: 'yarn'

      - run: yarn install --production=false --frozen-lockfile
      - uses: actions/download-artifact@v2
        with:
          name: build
          path: packages/
      - run: yarn deploy-storybook --dry-run
